## Numpy 데이터
### Numpy 행렬

In [5]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6]])   # 참조 형식임.

print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int32


### ndarray클래스 - N차원 배열

``` python
# array 함수 정의
np.array( object, dtype = None, copy = True, order = 'K', subok = False, ndmin = 0 )
```

In [9]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([1, 2, 3], dtype=complex, ndmin=3)    # complex: 복소수 형태
array3 = np.array(array1, copy=False)
array4 = np.array(np.mat('1 2; 3 4'), subok=True)

array1[0] = [4, 5, 6]

print(array1)
print(array2)
print(array3)
print(type(array4))

[[4 5 6]
 [4 5 6]]
[[[1.+0.j 2.+0.j 3.+0.j]]]
[[4 5 6]
 [4 5 6]]
<class 'numpy.matrix'>


### 배열의 개별 단위 요소에 접근하기

- 새로운 ndarray 변수에 객체를 덮어씌울 경우 원본 참조(얕은 복사)
- np.array의 copy매개변수는 깊은 복사로 객체를 복제

In [11]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1,2],
                   [3, 4]])
array3 = np.array([[[1, 2],
                    [3, 4],
                    [5, 6],
                    [7, 8]]])

print(array1[-1])
print(array2[0][1])
print(array3[0][1][1])

3
2
4


### 배열의 블록 단위 요소에 접근하기

In [12]:
array = np.array([[[1,2],
                   [3,4],
                   [5,6],
                   [7,8]]])

for i in array[0]:
    for j in i:
        if j % 2 == 0:
            print(j)

2
4
6
8


In [14]:
array = np.array([[1,2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]])

print(array[1:3])
print(array[::2])
print(array[2:, 1::2])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[12 14]
 [17 19]]


### 배열 차원 변형 
#### 배열의 차원 변형 reshape()

In [18]:
array = np.arange(12)

reshape1 = array.reshape(2, 3, 2)
reshape2 = np.reshape(array, (2,-1), order ='F')    # -1은 결정되는 값 할당

print(reshape1)
print(reshape2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


#### 배열의 차원 확장 (newaxis)

In [21]:
array = np.arange(4)

axis1 = array[np.newaxis]
axis2 = array[:, np.newaxis]

print(axis1)
print(axis2)

[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


#### 배열의 차원 축소

In [27]:
array = np.arange(12).reshape(3, -1)

flat1 = array.flatten(order='F')    # 메모리 레이아웃 Fortran 스타일
flat2 = array.ravel()               # C스타일

print(array)
print(flat1)
print(flat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  4  8  1  5  9  2  6 10  3  7 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### 배열 병합 및 분리

In [34]:
array1 = np.arange(6).reshape(2,3)
array2 = np.arange(6, 12).reshape(2,3)

merge1 = np.stack([array1, array2], axis=0)
merge2 = np.stack([array1, array2], axis=-1)
print(merge1, "\n\n")
print(merge2)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] 


[[[ 0  6]
  [ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]
  [ 5 11]]]


In [36]:
array = np.arange(10).reshape(2,5)

# np.split(array, index, axis=n)
detach1 = np.split(array, 2, axis=0)
# np.split(array, sections, axis=n)
detach2 = np.split(array, [2,3], axis=1)

print(detach1)
print(detach2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]
[array([[0, 1],
       [5, 6]]), array([[2],
       [7]]), array([[3, 4],
       [8, 9]])]


### 배열 연산

- math 라이브러리는 실수에 대해서만 연산을 지원.  
컨테이너 자료형에 대해서는 연산이 불가능. 반복문 등으로 배열 연산을 수행.  

- Numpy배열은 **범용 함수**를 제공.  
범용함수는 **브로드캐스팅** 및 **형식 캐스팅**기능을 ndarray클래스로 지원,  
배열의 요소별 연산을 고속으로 수행하는 벡터화된 **래퍼 함수**

    - 브로드캐스팅  
    Numpy배열에서 차원의 크기가 서로 다른 배열에서도 산술 연산이 가능하게 하는 원리
        1. 차원이 더 낮은 배열이 더 높은 배열과 같은 차원의 배열로 인식된다. ex)  (1,2)와 (1,4,2)의 연산 => (1,1,2)와 (1,4,2)의 연산 
        2. 반환된 배열은 연산을 수행한 배열 중 차원의 수(ndim)가 가장 큰 배열이 된다.
        3. 연산에 사용된 배열과 반환된 배열의 차원의 크기(shape)가 같거나 1일 경우 브로드캐스팅이 가능.
        4. 브로드캐스팅에 적용된 배열의 차원 크기는 연산에 사용된 배열의 차원의 크기에 대한 최소 공배수
        ex) (6, 2, 1), (2, 3) => (6, 2, 1), (1, 2, 3) => (6, 2, 3)
    - 형식 캐스팅  
    두 배열의 자료형을 비교해 표현 범위가 더 넓은 자료형을 선택하는 것.



In [42]:
array1 = np.array([1,2,3,4]).reshape(2,2)
array2 = np.array([1.5, 2.5])

add = array1 + array2

print(add)

[[2.5 4.5]
 [4.5 6.5]]


규칙 1: 두 배열의 차원 수가 다르면, 형태가 더 작은 배열의 앞에 1을 추가하여 차원 수를 맞춥니다.  
  - array2의 형태는 원래 (2,)입니다. 이를 (1, 2)로 변경하여 차원 수를 맞춥니다.

규칙 2: 특정 차원에서 크기가 1인 배열은 그 차원에 대해 반복되어 다른 배열의 크기에 맞춰집니다.  
  - array2가 (1, 2)로 변경된 후, 첫 번째 차원(행)을 따라 array1의 크기인 2에 맞추기 위해 반복됩니다. 즉, array2는 이제 [[1.5, 2.5], [1.5, 2.5]]와 같이 간주됩니다.

규칙 3: 모든 차원에서 크기가 일치하거나, 그 차원의 크기가 1인 경우에만 두 배열 간의 연산이 가능합니다.

### matrix 클래스
행렬 연산에 특화된 2차원 배열.

1. ndarray 클래스와의 차이점  
ndarray 클래스에서는 곱(\*)과 제곱(\*\*) 연산을 각 원소에 대해 수행  
matrix 클래스에서는 곱(\*)과 제곱(\*\*)을 행렬 간의 연산으로 처리

2.속성
- *.T : 전치
- *.H : 공액 복소수 전치
- *.I : 곱의 역함수,
- *.A : ndarray 클래스로 변환

** Numpy라이브러리에서는 matrix 클래스의 사용을 권장하지 않음. 가능하다면 ndarray클래스를 사용해 연산을 처리

In [44]:
arrray1 = np.array([1,2,3,4]).reshape(2,2)
array2 = np.array([5,6,7,8]).reshape(2,2)

mat1 = np.mat(array1)
mat2 = np.mat(array2)

print(mat1.T * mat2)
print(mat1 ** 2)

[[26 30]
 [38 44]]
[[ 7 10]
 [15 22]]


### 관심영역

In [46]:
array = np.zeros((1280, 1920, 3), np.uint8)

x, y, w, h = 100, 100, 300, 300
roi = array[x:x+w, y:y+h]

print(array.shape)
print(roi.shape)

(1280, 1920, 3)
(300, 300, 3)


### 관심 채널

In [47]:
array = np.zeros((1280, 1920, 3), np.uint8)

coi = array[:,:,0]

print(array.shape)
print(coi.shape)

(1280, 1920, 3)
(1280, 1920)
